"""esquema inicial

Revision ID: 7a6c2c8a2066
Revises: 
Create Date: 2026-07-13 22:31:03.945842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a6c2c8a2066'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festivo',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('es_festivo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha')
    )
    op.create_table('parametro_legal',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('norma', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parametro_legal_codigo'), 'parametro_legal', ['codigo'], unique=False)
    op.create_table('periodo_liquidacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=10), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fecha_inicio', 'fecha_fin')
    )
    op.create_table('unidad_residencial',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('empleado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('unidad_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('tipo_documento', sa.String(length=5), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('salario_base', sa.BigInteger(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad_residencial.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('documento')
    )
    op.create_table('liquidacion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('periodo_id', sa.Uuid(), nullable=False),
    sa.Column('unidad_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parametros_snapshot', sa.JSON(), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['periodo_id'], ['periodo_liquidacion.id'], ),
    sa.ForeignKeyConstraint(['unidad_id'], ['unidad_residencial.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('periodo_id', 'unidad_id', 'version')
    )
    op.create_table('liquidacion_empleado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('liquidacion_id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('nombre_empleado', sa.String(length=200), nullable=False),
    sa.Column('salario_mensual', sa.BigInteger(), nullable=False),
    sa.Column('tarifa_hora', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['liquidacion_id'], ['liquidacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_liquidacion_empleado_liquidacion_id'), 'liquidacion_empleado', ['liquidacion_id'], unique=False)
    op.create_table('turno',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('empleado_id', sa.Uuid(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turno_empleado_id'), 'turno', ['empleado_id'], unique=False)
    op.create_index(op.f('ix_turno_fecha'), 'turno', ['fecha'], unique=False)
    op.create_table('concepto_liquidado',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('liquidacion_empleado_id', sa.Uuid(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('minutos', sa.Integer(), nullable=False),
    sa.Column('tarifa_hora', sa.String(length=30), nullable=True),
    sa.Column('factor', sa.String(length=15), nullable=True),
    sa.Column('componentes', sa.JSON(), nullable=False),
    sa.Column('valor', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['liquidacion_empleado_id'], ['liquidacion_empleado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concepto_liquidado_liquidacion_empleado_id'), 'concepto_liquidado', ['liquidacion_empleado_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_concepto_liquidado_liquidacion_empleado_id'), table_name='concepto_liquidado')
    op.drop_table('concepto_liquidado')
    op.drop_index(op.f('ix_turno_fecha'), table_name='turno')
    op.drop_index(op.f('ix_turno_empleado_id'), table_name='turno')
    op.drop_table('turno')
    op.drop_index(op.f('ix_liquidacion_empleado_liquidacion_id'), table_name='liquidacion_empleado')
    op.drop_table('liquidacion_empleado')
    op.drop_table('liquidacion')
    op.drop_table('empleado')
    op.drop_table('unidad_residencial')
    op.drop_table('periodo_liquidacion')
    op.drop_index(op.f('ix_parametro_legal_codigo'), table_name='parametro_legal')
    op.drop_table('parametro_legal')
    op.drop_table('festivo')
    # ### end Alembic commands ###
