"""seguridad: usuario, sesion y auditoria

Revision ID: 7e6140cb7851
Revises: 7a6c2c8a2066
Create Date: 2026-07-14 10:29:17.846270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e6140cb7851'
down_revision: Union[str, Sequence[str], None] = '7a6c2c8a2066'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_email', sa.String(length=200), nullable=False),
    sa.Column('accion', sa.String(length=40), nullable=False),
    sa.Column('entidad', sa.String(length=40), nullable=False),
    sa.Column('entidad_id', sa.String(length=40), nullable=False),
    sa.Column('antes', sa.JSON(), nullable=True),
    sa.Column('despues', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sesion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('expira_en', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creada_en', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sesion_usuario_id'), 'sesion', ['usuario_id'], unique=False)
    # ### end Alembic commands ###

    # La auditoría es APPEND-ONLY: la propia base de datos rechaza UPDATE/DELETE.
    if op.get_bind().dialect.name == "sqlite":
        op.execute(
            "CREATE TRIGGER auditoria_sin_update BEFORE UPDATE ON auditoria "
            "BEGIN SELECT RAISE(ABORT, 'auditoria es append-only'); END"
        )
        op.execute(
            "CREATE TRIGGER auditoria_sin_delete BEFORE DELETE ON auditoria "
            "BEGIN SELECT RAISE(ABORT, 'auditoria es append-only'); END"
        )
    else:  # PostgreSQL
        op.execute(
            "CREATE OR REPLACE FUNCTION auditoria_bloquear() RETURNS trigger AS $$ "
            "BEGIN RAISE EXCEPTION 'auditoria es append-only'; END; "
            "$$ LANGUAGE plpgsql"
        )
        op.execute(
            "CREATE TRIGGER auditoria_inmutable BEFORE UPDATE OR DELETE ON auditoria "
            "FOR EACH ROW EXECUTE FUNCTION auditoria_bloquear()"
        )


def downgrade() -> None:
    """Downgrade schema."""
    if op.get_bind().dialect.name == "sqlite":
        op.execute("DROP TRIGGER IF EXISTS auditoria_sin_update")
        op.execute("DROP TRIGGER IF EXISTS auditoria_sin_delete")
    else:
        op.execute("DROP TRIGGER IF EXISTS auditoria_inmutable ON auditoria")
        op.execute("DROP FUNCTION IF EXISTS auditoria_bloquear")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sesion_usuario_id'), table_name='sesion')
    op.drop_table('sesion')
    op.drop_table('usuario')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
