from __future__ import annotations

from datetime import date, time
from decimal import Decimal
from typing import Protocol


class ProveedorParametros(Protocol):
    """Puerto del motor de cálculo: valores legales vigentes EN LA FECHA dada.

    `ConjuntoParametros` (dominio) lo implementa en memoria; en Fase 2 lo
    implementará un repositorio sobre la tabla de parámetros.
    """

    def jornada_nocturna(self, fecha: date) -> tuple[time, time]: ...
    def recargo_nocturno(self, fecha: date) -> Decimal: ...
    def extra_diurna(self, fecha: date) -> Decimal: ...
    def extra_nocturna(self, fecha: date) -> Decimal: ...
    def recargo_dominical_festivo(self, fecha: date) -> Decimal: ...
    def jornada_maxima_semanal(self, fecha: date) -> Decimal: ...
    def horas_quincena(self, fecha: date) -> Decimal: ...
    def divisor_hora_ordinaria(self, fecha: date) -> Decimal: ...
    def auxilio_transporte_mensual(self, fecha: date) -> Decimal: ...
    def estrategia_clasificacion_extras(self, fecha: date) -> str: ...
