"""Puertos de persistencia: la infraestructura los implementa con SQLAlchemy;
los casos de uso solo conocen estos contratos."""

from __future__ import annotations

from datetime import date
from typing import Protocol
from uuid import UUID

from nomina.dominio.entidades.empleado import Empleado
from nomina.dominio.entidades.parametro_legal import ParametroLegal
from nomina.dominio.entidades.periodo_liquidacion import PeriodoLiquidacion
from nomina.dominio.entidades.turno import TurnoRegistrado
from nomina.dominio.entidades.unidad_residencial import UnidadResidencial


class RepositorioUnidades(Protocol):
    def guardar(self, unidad: UnidadResidencial) -> None: ...
    def obtener(self, id: UUID) -> UnidadResidencial | None: ...
    def listar(self) -> list[UnidadResidencial]: ...


class RepositorioEmpleados(Protocol):
    def guardar(self, empleado: Empleado) -> None: ...
    def obtener(self, id: UUID) -> Empleado | None: ...
    def listar(self, unidad_id: UUID | None = None, solo_activos: bool = False) -> list[Empleado]: ...


class RepositorioPeriodos(Protocol):
    def guardar(self, periodo: PeriodoLiquidacion) -> None: ...
    def obtener(self, id: UUID) -> PeriodoLiquidacion | None: ...
    def listar(self) -> list[PeriodoLiquidacion]: ...
    def que_contiene(self, fecha: date) -> PeriodoLiquidacion | None: ...


class RepositorioTurnos(Protocol):
    def guardar(self, turno: TurnoRegistrado) -> None: ...
    def obtener(self, id: UUID) -> TurnoRegistrado | None: ...
    def eliminar(self, id: UUID) -> bool: ...
    def de_empleado_entre(self, empleado_id: UUID, desde: date, hasta: date) -> list[TurnoRegistrado]: ...


class RepositorioParametros(Protocol):
    def listar(self) -> list[ParametroLegal]: ...
    def agregar(self, parametro: ParametroLegal) -> None: ...
    def cerrar_vigencia_abierta(self, codigo: str, hasta: date) -> None: ...


class RepositorioFestivos(Protocol):
    def agregar_ajuste(self, fecha: date, nombre: str, es_festivo: bool) -> None: ...
    def eliminar_ajuste(self, fecha: date) -> bool: ...
    def ajustes(self) -> tuple[frozenset[date], frozenset[date]]:
        """(fechas agregadas manualmente, fechas anuladas del cálculo legal)."""
        ...
